//! Yew web demo of the connetto browser topology, end to end.
//!
//! Every window runs the same app. One window wins the Web Locks leader
//! election and spawns the dedicated DB worker, the only browsing context kind
//! with OPFS sync access handles. That worker owns the durable replica, the
//! server connection, the relay hub, and the device-private local tier. Every
//! window, leader or follower, connects a tab client to the worker over its
//! own `BroadcastChannel` and runs live queries against a local SQLite mirror.
//!
//! The synced `orders` list converges across every window of every device
//! through Postgres logical replication: a tab write rides the hub up to the
//! worker, applies to Postgres, and echoes back through CDC to every window.
//! The device-private `notes` list converges across the windows of one device
//! through the hub alone and never reaches the server: the worker replica does
//! not even contain the table.
//!
//! The DB worker shares this same wasm module: [`main`] finds no `Window` in a
//! worker context, where Yew cannot run, and boots the DB tier through
//! `run_db_worker` instead of rendering the UI. The bootstrap that imports the
//! glue is generated by `connetto-web` (`WorkerBootstrap::Generated`), since
//! trunk's glue does not initialize itself.
//!
//! Run against the demo stack (dev IdP, server on 7777, `connetto-demo-pg` on
//! 55456): start the dev IdP with `CONNETTO_AUTH_BIND=127.0.0.1:18081` set,
//! source `target/dev-idp.env`, start the server with `CONNETTO_AUTH`,
//! `CONNETTO_AUTH_BIND`, the OIDC provider vars from `target/dev-idp.env`,
//! `CONNETTO_READER_URL`, `DATABASE_URL`, `CONNETTO_BIND`, `CONNETTO_WRITABLE`, and
//! `CONNETTO_PG_DDL_FILE`, then `trunk serve` from this directory and open
//! the served URL in several windows.

use std::rc::Rc;

use connetto_client::reconnect::ReconnectPolicy;
use connetto_client::teardown::expiry_warning;
use connetto_client::{
    ClientConfig, ClientEvent, ConnettoClient, ConnettoConnection, ExportScope, PolicyTables,
    Replica,
};
use connetto_core::custody::Custody;
use connetto_web::auth::WorkerAuthConfig;
use connetto_web::unlock::{AccountChoice, serve_account_choice};
use connetto_web::{MessageTransport, deliver_login_code, leader, locks, workers};
use connetto_yew::use_live;
use diesel::prelude::*;
use wasm_bindgen::closure::Closure;
use wasm_bindgen::prelude::*;
use wasm_bindgen_futures::spawn_local;
use web_sys::{BroadcastChannel, Event, HtmlInputElement, MessageEvent};

include!(concat!(env!("OUT_DIR"), "/replica-tables.rs"));
use yew::prelude::*;

/// The tab-to-worker transport this window's client rides.
type Tab = MessageTransport<BroadcastChannel>;

/// The demo server the DB worker connects upstream to.
const DEMO_WS_URL: &str = "ws://127.0.0.1:7777/";
/// The origin serving `connetto-server`'s auth router, which the login navigation
/// goes to directly. The worker's `fetch` calls go through this app's own origin
/// instead, where the dev server proxies them.
const AUTH_ORIGIN: &str = "http://127.0.0.1:18081";
/// The Postgres schema source the demo server is launched with. Hashing it
/// yields the version the server advertises, so this build presents a matching
/// version at handshake and is not rejected as stale.
const SCHEMA_SQL: &str = include_str!("../schema.sql");
/// The synced replica schema (worker first boot). Matches `schema.sql`.
const DEMO_SQLITE_DDL: &str = "CREATE TABLE orders (id BLOB PRIMARY KEY DEFAULT (uuidv4()) CHECK (length(id) = 16) NOT NULL, quantity INTEGER NOT NULL CHECK (quantity >= 0)) STRICT; \
     CREATE TABLE order_lines (order_id BLOB NOT NULL REFERENCES orders(id) CHECK (length(order_id) = 16), line_no INTEGER NOT NULL, quantity INTEGER NOT NULL CHECK (quantity >= 0), PRIMARY KEY (order_id, line_no)) STRICT;";
/// The tab mirror schema: both tiers in the tab's main schema, because every
/// relayed patch applies to main. The hub, not the tab, keeps the tiers apart.
const DEMO_TAB_DDL: &str = "CREATE TABLE orders (id BLOB PRIMARY KEY DEFAULT (uuidv4()) CHECK (length(id) = 16) NOT NULL, quantity INTEGER NOT NULL CHECK (quantity >= 0)) STRICT; \
     CREATE TABLE order_lines (order_id BLOB NOT NULL REFERENCES orders(id) CHECK (length(order_id) = 16), line_no INTEGER NOT NULL, quantity INTEGER NOT NULL CHECK (quantity >= 0), PRIMARY KEY (order_id, line_no)) STRICT; \
     CREATE TABLE notes (id INTEGER PRIMARY KEY NOT NULL, body TEXT) STRICT;";
/// The upstream subscription the worker registers.
const DEMO_QUERY: &str = "SELECT * FROM orders WHERE quantity > 0";
/// The OPFS file holding the worker's durable synced replica.
const DB_NAME: &str = "connetto-relay.sqlite";
/// The shared leader lock every window of this app races.
const LEADER_LOCK: &str = "connetto-demo-leader";
/// The local tier schema, translated from `frontend.sql` by build.rs. DDL rather
/// than a baked template, because a tier encrypted at rest cannot be seeded from
/// a plaintext byte image.
const FRONTEND_DDL: &str = include_str!(concat!(env!("OUT_DIR"), "/frontend-ddl.sql"));
/// The `BroadcastChannel` the worker uses to report the boot session to all page
/// tabs after authentication, so they can show the account, custody level, and
/// expiry information.
const DEMO_IDENTITY_CHANNEL: &str = "connetto-demo-identity";
/// OIDC provider registered in the dev IdP.
const AUTH_PROVIDER: &str = "dev-idp";
/// Channel the page uses to respond to the worker's provider query at each boot.
const DEMO_PROVIDER_CHANNEL: &str = "connetto-demo-provider";
/// File name the export download is offered under.
const EXPORT_FILE_NAME: &str = "connetto-local-data.zip";

diesel::table! {
    orders (id) {
        id -> rosetta_uuid::sql_types::Uuid,
        quantity -> diesel::sql_types::BigInt,
    }
}

diesel::table! {
    notes (id) {
        id -> diesel::sql_types::BigInt,
        body -> diesel::sql_types::Text,
    }
}

#[derive(Queryable, Selectable, Debug, PartialEq, Clone)]
#[diesel(table_name = orders)]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
struct Order {
    id: rosetta_uuid::Uuid,
    quantity: i64,
}

#[derive(Queryable, Selectable, Debug, PartialEq, Clone)]
#[diesel(table_name = notes)]
#[diesel(check_for_backend(diesel::sqlite::Sqlite))]
struct Note {
    id: i64,
    body: String,
}

// The synced key generator: `orders.id` bakes to `DEFAULT (uuidv4())`, so a
// tab write omits the id and this registered function mints it. The impl is
// `rosetta_uuid::Uuid::new_v4`, the same strongly typed key the `orders` schema
// uses on SQLite and Postgres.
#[diesel::declare_sql_function]
extern "SQL" {
    /// Client-authored primary key: a 16-byte UUID v4, stored as a BLOB.
    fn uuidv4() -> diesel::sql_types::Binary;
}

/// The registrar connetto installs on every connection it opens for this app.
/// Nondeterministic, so SQLite calls `uuidv4()` per row instead of folding the
/// DEFAULT to a constant, and `INNOCUOUS` because the replica runs with trusted
/// schema off and a column DEFAULT is a schema object.
fn uuidv4_functions() -> connetto_client::SqlFunctions {
    connetto_client::SqlFunctions::new().with(std::sync::Arc::new(
        |conn: &mut diesel::SqliteConnection| {
            uuidv4_utils::register_impl_with_behavior(
                conn,
                diesel::sqlite::SqliteFunctionBehavior::INNOCUOUS,
                rosetta_uuid::Uuid::new_v4,
            )
        },
    ))
}

/// A device-unique integer id for a local-only `notes` row. `notes` stays on
/// integer keys (device-private, never synced), so the client authors the id.
/// The millisecond clock plus a random low tag keeps two windows of one device
/// from colliding within the same millisecond.
fn fresh_note_id() -> i64 {
    let now = js_sys::Date::now();
    debug_assert!(now.is_finite() && now >= 0.0);
    // Intended truncation: whole milliseconds since the epoch.
    let millis = now as i64;
    let tag = js_sys::Math::random() * 1000.0;
    // Math::random is [0, 1); scale to a 0..=999 tag. Deliberate quantization.
    debug_assert!(tag.is_finite() && (0.0..1000.0).contains(&tag));
    millis * 1000 + tag as i64
}

/// A visible order quantity inside the subscription's `quantity > 0` window.
///
/// The id is minted by the DEFAULT now, so quantity cannot key off it. A random
/// `1..=9` times five gives spread while staying strictly positive.
fn fresh_quantity() -> i64 {
    let scaled = js_sys::Math::random() * 9.0;
    // Math::random is [0, 1); scale to 0..=8. Deliberate truncation.
    debug_assert!(scaled.is_finite() && (0.0..9.0).contains(&scaled));
    (scaled as i64 + 1) * 5
}

/// The tab mirror's physical footprint: total pages and free pages a trim can reclaim.
async fn replica_footprint(client: &ConnettoClient<Tab>) -> (i64, i64) {
    client
        .with_conn(|conn| {
            let db = conn.conn();
            let pages = db.page_count(None).unwrap_or(0);
            let free = db.freelist_count(None).unwrap_or(0);
            (pages, free)
        })
        .await
}

fn main() {
    connetto_web::logging::init_console();
    // The dedicated DB worker runs this same wasm module. A worker has no
    // Window, so boot the DB tier there instead of rendering the UI.
    if web_sys::window().is_none() {
        spawn_local(async {
            if let Err(err) = run_db_worker().await {
                tracing::error!(error = ?err, "db worker failed");
            }
        });
        return;
    }

    let win = web_sys::window().expect("window context");

    // OAuth popup callback: the auth popup lands here with ?code=&state= after
    // the user authenticates. Deliver the code to the waiting worker, then
    // close the popup so the original window continues uninterrupted.
    //
    // A same-window redirect (no opener) is handled the same way: deliver the
    // code, clear the query string, and fall through to render the app. In
    // practice the popup path is used so the original worker keeps its PKCE
    // state and can verify the returned state parameter.
    let search = win.location().search().unwrap_or_default();
    if let (Some(code), Some(state)) = (query_param(&search, "code"), query_param(&search, "state"))
    {
        let _ = deliver_login_code(&code, &state);

        // If this window was opened by window.open() for the auth popup, close
        // it now that the code has been delivered to the original window's worker.
        let has_opener = js_sys::Reflect::get(win.as_ref(), &"opener".into())
            .map(|v| !v.is_null() && !v.is_undefined())
            .unwrap_or(false);
        if has_opener {
            let _ = win.close();
            return;
        }

        // Not a popup: clear the query string so a reload does not re-deliver
        // an already-spent code.
        let pathname = win.location().pathname().unwrap_or_else(|_| "/".to_owned());
        if let Ok(history) = win.history() {
            let _ = history.replace_state_with_url(&JsValue::NULL, "", Some(&pathname));
        }
    }

    yew::Renderer::<App>::new().render();
}

/// Worker context: ask the page which OIDC provider to use for this boot.
///
/// The page responds with the user's last choice within a few milliseconds.
/// Falls back to [`AUTH_PROVIDER`] after 200 ms so a page that never answers
/// does not stall the boot indefinitely.
async fn worker_provider() -> String {
    let Ok(ch) = BroadcastChannel::new(DEMO_PROVIDER_CHANNEL) else {
        return AUTH_PROVIDER.to_owned();
    };
    let received: std::rc::Rc<std::cell::RefCell<Option<String>>> =
        std::rc::Rc::new(std::cell::RefCell::new(None));
    let received_clone = std::rc::Rc::clone(&received);
    let on_msg = Closure::<dyn FnMut(MessageEvent)>::new(move |e: MessageEvent| {
        if let Some(text) = e.data().as_string()
            && text != "provider?"
        {
            *received_clone.borrow_mut() = Some(text);
        }
    });
    ch.set_onmessage(Some(on_msg.as_ref().unchecked_ref()));
    let _ = ch.post_message(&JsValue::from_str("provider?"));
    for _ in 0..8 {
        workers::sleep(core::time::Duration::from_millis(25)).await;
        if received.borrow().is_some() {
            break;
        }
    }
    ch.set_onmessage(None);
    ch.close();
    drop(on_msg);
    received
        .borrow()
        .clone()
        .unwrap_or_else(|| AUTH_PROVIDER.to_owned())
}

/// Boot the connetto DB tier in the worker context with the demo config.
///
/// # Errors
///
/// A JS string describing the VFS, upstream connect, or subscribe failure.
async fn run_db_worker() -> Result<(), JsValue> {
    let origin = worker_origin();
    let auth = Some(
        WorkerAuthConfig::new(
            origin.clone(),
            worker_provider().await,
            format!("{origin}/"),
        )
        // The login is a navigation; trunk's proxy does not forward a request
        // that carries a query string, so it goes straight to the auth origin.
        .with_login_base_url(Some(AUTH_ORIGIN.to_owned())),
    );
    let session = workers::boot_db_worker::<String>(
        &workers::DbWorkerConfig::new(connetto_core::SchemaVersion::from_source(SCHEMA_SQL))
            .with_ws_url(DEMO_WS_URL)
            .with_replica_db_prefix(DB_NAME)
            .with_replica_ddl(DEMO_SQLITE_DDL)
            .with_frontend_ddl(FRONTEND_DDL)
            .with_upstream_sub_id("db-upstream")
            .with_upstream_query(DEMO_QUERY)
            .with_hub_meta_name("connetto-hub-meta.sqlite")
            .with_sql_functions(uuidv4_functions())
            .with_policy_tables(PolicyTables::from_translation(
                POLICY_TABLES.iter().copied(),
                POLICY_VIEWS.iter().copied(),
            ))
            .with_auth(auth)
            .with_auth_db_name("connetto-auth.sqlite")
            .with_unlock(true)
            .with_pick_account(true),
    )
    .await?;
    // Broadcast so every tab can show the account, expiry info, and custody level.
    broadcast_boot_session(
        session.identity.as_deref(),
        session.session_expires_at,
        session.account.as_deref(),
    );
    Ok(())
}

/// Worker context: broadcast the authenticated identity and session metadata to
/// every page tab over the shared identity channel.
///
/// The message is a JSON object with optional `identity`, `expiresAt` (string
/// encoding of unix seconds, avoiding float precision loss), and `account` fields.
fn broadcast_boot_session(
    identity: Option<&str>,
    session_expires_at: Option<u64>,
    account: Option<&str>,
) {
    if let Ok(ch) = BroadcastChannel::new(DEMO_IDENTITY_CHANNEL) {
        let obj = js_sys::Object::new();
        if let Some(id) = identity {
            js_sys::Reflect::set(&obj, &"identity".into(), &id.into()).ok();
        }
        if let Some(exp) = session_expires_at {
            // Send as a string to avoid u64 -> f64 precision loss for far-future timestamps.
            js_sys::Reflect::set(&obj, &"expiresAt".into(), &exp.to_string().into()).ok();
        }
        if let Some(acc) = account {
            js_sys::Reflect::set(&obj, &"account".into(), &acc.into()).ok();
        }
        if let Ok(json) = js_sys::JSON::stringify(&obj.into())
            && let Some(s) = json.as_string()
        {
            let _ = ch.post_message(&JsValue::from_str(&s));
        }
        ch.close();
    }
}

/// Parse one query-string parameter from a `?key=value&...` search string.
fn query_param(search: &str, key: &str) -> Option<String> {
    search.trim_start_matches('?').split('&').find_map(|pair| {
        let (k, v) = pair.split_once('=')?;
        (k == key).then(|| v.to_owned())
    })
}

/// Reload the page after logout or an account switch.
fn reload_page() {
    if let Some(win) = web_sys::window() {
        let _ = win.location().reload();
    }
}

/// The origin of the worker's own URL, e.g. `http://127.0.0.1:9911`.
///
/// Same as the page origin because the worker script is served from the same
/// host. Used to build `WorkerAuthConfig` within the worker.
fn worker_origin() -> String {
    js_sys::eval("self.location.origin")
        .ok()
        .and_then(|v| v.as_string())
        .unwrap_or_default()
}

/// Offer `bytes` to the user as a file download named `name`.
///
/// A `Blob` at an object URL plus a synthetic anchor click, which is the only
/// way a page can hand over a file the user decides where to keep. The URL is
/// revoked immediately: the click has already taken its own reference.
fn download_bytes(name: &str, bytes: &[u8]) -> Result<(), JsValue> {
    let parts = js_sys::Array::new();
    parts.push(&js_sys::Uint8Array::from(bytes));
    let blob = web_sys::Blob::new_with_u8_array_sequence(&parts)?;
    let url = web_sys::Url::create_object_url_with_blob(&blob)?;
    let document = web_sys::window()
        .and_then(|window| window.document())
        .ok_or_else(|| JsValue::from_str("no document"))?;
    let anchor: web_sys::HtmlAnchorElement = document.create_element("a")?.dyn_into()?;
    anchor.set_href(&url);
    anchor.set_download(name);
    anchor.click();
    web_sys::Url::revoke_object_url(&url)
}

/// The served URL of this app's wasm-bindgen glue module, recovered from the
/// wasm fetch the page already performed. Under trunk the glue is
/// `/<name>-<hash>.js` beside `/<name>-<hash>_bg.wasm`, so the wasm resource
/// entry names the glue by suffix swap. Only the main thread can see these
/// entries, which is why the worker receives the glue URL as a spawn parameter.
fn glue_url() -> String {
    let found = js_sys::eval(
        r#"performance.getEntriesByType("resource").map((e) => e.name).find((n) => n.endsWith("_bg.wasm"))"#,
    )
    .ok()
    .and_then(|value| value.as_string())
    .expect("a loaded wasm resource entry");
    let base = found.strip_suffix("_bg.wasm").expect("wasm suffix");
    format!("{base}.js")
}

/// The window's live connection to the DB worker, plus the topology tokens it
/// must keep alive: leadership (this window may own the worker) and the tab
/// liveness lock (dropped on unmount, so the worker reaps this tab).
struct Boot {
    client: ConnettoClient<Tab>,
    _membership: leader::Membership,
    _tab_lock: locks::HeldLock,
    /// Passkey custody level as of this boot, read from the worker after it settled.
    custody: Custody,
}

/// Join the topology and connect this window's tab client.
///
/// The sequence mirrors what the browser test suite pins: join the leader
/// election (the winner spawns the worker), wait for the worker to answer,
/// hold the tab liveness lock BEFORE connecting, connect over a boot wire, and
/// wrap the connection in the reconnecting client so a worker swap recovers.
async fn boot_window() -> Result<Boot, JsValue> {
    let glue = glue_url();
    let client_id = format!("tab-{}", js_sys::Date::now());

    // Trunk's glue does not self-initialize, so connetto-web spawns the worker
    // from a generated bootstrap that imports the glue and runs init.
    let membership = leader::join(LEADER_LOCK, &glue, workers::WorkerBootstrap::Generated);
    workers::await_db_worker_ready().await?;
    // Read custody after the worker has settled, while still on the hello channel.
    let custody = workers::request_custody().await;

    let tab_lock = locks::hold_lock(&locks::tab_lock_name(&client_id)).await;
    let wire = format!("connetto-wire-{client_id}-boot");
    workers::announce_tab(&wire).await;
    let transport =
        MessageTransport::<BroadcastChannel>::with_peer_liveness(&wire, workers::DB_ALIVE_LOCK)
            .map_err(|err| JsValue::from_str(&err.to_string()))?;
    let config = ClientConfig::new(client_id.clone())
        .with_schema_version(Some(connetto_core::SchemaVersion::from_source(SCHEMA_SQL)))
        .with_sql_functions(uuidv4_functions())
        .with_policy_tables(PolicyTables::from_translation(
            POLICY_TABLES.iter().copied(),
            POLICY_VIEWS.iter().copied(),
        ))
        // A low threshold so the free-up-space affordance reclaims after a
        // modest deletion, rather than only once the freelist is a quarter of
        // the file. Trimming still runs only when the pass is called.
        .with_trim_threshold(5);
    let conn = ConnettoConnection::connect(
        transport,
        &Replica::in_memory(),
        DEMO_TAB_DDL,
        &config,
        None,
    )
    .await
    .map_err(|err| JsValue::from_str(&err.to_string()))?;
    let policy = ReconnectPolicy::new()
        .with_initial_backoff(core::time::Duration::from_millis(100))
        .with_max_backoff(core::time::Duration::from_secs(2));
    let (client, pump) = ConnettoClient::with_reconnect(
        conn,
        workers::tab_wire_factory(client_id),
        workers::sleep,
        policy,
    );
    spawn_local(pump);
    Ok(Boot {
        client,
        _membership: membership,
        _tab_lock: tab_lock,
        custody,
    })
}

/// A short status line word for one client event, or `None` to ignore it.
fn status_label(event: &ClientEvent) -> Option<String> {
    match event {
        ClientEvent::Reconnecting { attempt } => Some(format!("reconnecting (attempt {attempt})")),
        ClientEvent::Reconnected => Some("reconnected".to_owned()),
        ClientEvent::MutationApplied { client_seq } => {
            Some(format!("mutation {client_seq} applied"))
        }
        ClientEvent::MutationRejected { client_seq, .. } => {
            Some(format!("mutation {client_seq} rejected"))
        }
        ClientEvent::MutationConflict {
            client_seq,
            server_row,
            ..
        } => Some(server_row.as_ref().map_or_else(
            || format!("mutation {client_seq} conflicted, the server row is gone"),
            |row| {
                format!(
                    "mutation {client_seq} conflicted, the server holds {}",
                    row.row_json
                )
            },
        )),
        // The reconnect policy uses its own fixed backoff and does not read
        // retry_after_ms. This shows the value so the user can see what the
        // server asked for, even though nothing here acts on it automatically.
        ClientEvent::RateLimited { retry_after_ms, .. } => Some(format!(
            "rate limited, server asks to wait {retry_after_ms} ms before retrying"
        )),
        ClientEvent::ServerClosed {
            reason: connetto_core::messages::FatalErrorReason::RateLimited { retry_after_ms },
        } => Some(format!(
            "connection closed: exceeded rate limit, server asks to wait {retry_after_ms} ms"
        )),
        ClientEvent::ServerClosed { reason } => {
            Some(format!("server closed the session: {reason:?}"))
        }
        ClientEvent::Closed => Some("connection closed".to_owned()),
        _ => None,
    }
}

/// Styling kept minimal: the demo is the topology, not the paint.
const CSS: &str = r"
    body { font-family: sans-serif; margin: 0; }
    .wrap { padding: 16px; max-width: 720px; margin: 0 auto; }
    .panes { display: flex; gap: 16px; flex-wrap: wrap; }
    .pane { flex: 1 1 300px; border: 1px solid #ccc; border-radius: 8px; padding: 12px; }
    .pane h2 { margin-top: 0; font-size: 1.1em; }
    .badge { font-size: 0.7em; padding: 2px 6px; border-radius: 4px; vertical-align: middle; }
    .synced { background: #e6f0ff; color: #14458c; }
    .local { background: #fde6e6; color: #8c1414; }
    .trim { background: #eef7e6; color: #2e6b14; }
    .status { color: #555; font-family: monospace; }
    table { border-collapse: collapse; width: 100%; margin-top: 8px; }
    th, td { border: 1px solid #ddd; padding: 4px 8px; text-align: left; }
    input { padding: 4px; }
    button { padding: 4px 10px; cursor: pointer; }
    .row { display: flex; gap: 6px; margin-top: 8px; flex-wrap: wrap; }
    .auth-bar { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; margin: 10px 0; padding: 8px; background: #f8f8f8; border-radius: 6px; }
    .picker { border: 1px solid #bbb; border-radius: 8px; padding: 12px; margin: 8px 0; background: #fffbe6; }
    .expiry-warn { border: 1px solid #e0a020; border-radius: 6px; padding: 8px 12px; background: #fff8e1; margin: 8px 0; }
";

/// A cheaply clonable, identity-compared client handle for props.
///
/// One window creates exactly one client and never replaces it, so pointer
/// identity is the right equality: [`Dashboard`] mounts once with it and
/// re-renders from its own live state, not from a prop change.
#[derive(Clone)]
struct ClientHandle(Rc<ConnettoClient<Tab>>);

impl PartialEq for ClientHandle {
    fn eq(&self, other: &Self) -> bool {
        Rc::ptr_eq(&self.0, &other.0)
    }
}

#[function_component(App)]
fn app() -> Html {
    let client = use_state(|| None::<ClientHandle>);
    let status = use_state(|| "connecting to the connetto stack".to_owned());
    // The boot tokens live as long as the app: dropping them on page close
    // resigns leadership and frees the tab lock, which reaps this tab.
    let boot_hold = use_mut_ref(|| None::<Boot>);

    // Identity and session metadata received from the worker after authentication.
    let identity = use_state(|| None::<String>);
    let booted_account = use_state(|| None::<String>);
    let session_expires_at = use_state(|| None::<u64>);

    // Passkey custody level, set once after boot_window returns.
    let custody = use_state(|| Custody::Ephemeral);

    // Session expiry warning: Some when the session is near its end and there
    // are unsynced writes that would be lost if it lapses.
    let expiry_warn = use_state(|| None::<connetto_client::teardown::ExpiryWarning>);

    // Login URL the worker broadcasts when interactive auth is needed.
    let login_url = use_state(|| None::<String>);

    // Confirmation state for the delete-data logout flow.
    let confirm_seqs = use_state(|| None::<Vec<u64>>);
    let refused_seqs = use_state(|| None::<Vec<u64>>);

    // Account chooser: the list of accounts the worker offered during the
    // last account question, shown as a picker while the chooser awaits.
    let account_picker = use_state(|| None::<Vec<String>>);
    // Accounts seen so far, kept for the switch-account controls in the auth bar.
    let known_accounts = use_state(Vec::<String>::new);
    // Shared cell between the chooser future and the picker UI: the UI writes
    // the user's choice here, the chooser loop reads and returns it.
    let pending_choice = use_mut_ref(|| None::<AccountChoice>);

    // Register the account chooser. Called on every render (just updates a
    // thread-local), so the captures always point at the current render's state.
    {
        let account_picker = account_picker.clone();
        let known_accounts = known_accounts.clone();
        let pending_choice = pending_choice.clone();
        serve_account_choice(move |accounts| {
            let account_picker = account_picker.clone();
            let known_accounts = known_accounts.clone();
            let pending_choice = pending_choice.clone();
            async move {
                // Clear any stale answer from a previous chooser call.
                *pending_choice.borrow_mut() = None;
                known_accounts.set(accounts.clone());
                account_picker.set(Some(accounts));
                // Poll until the user makes a choice through the picker UI.
                loop {
                    workers::sleep(core::time::Duration::from_millis(30)).await;
                    if let Some(choice) = pending_choice.borrow().clone() {
                        account_picker.set(None);
                        return choice;
                    }
                }
            }
        });
    }

    // Listen for the worker broadcasting the boot session (identity, expiry, account).
    {
        let identity = identity.clone();
        let booted_account = booted_account.clone();
        let session_expires_at = session_expires_at.clone();
        let expiry_warn = expiry_warn.clone();
        let client = client.clone();
        use_effect_with((), move |()| {
            let channel = BroadcastChannel::new(DEMO_IDENTITY_CHANNEL).expect("identity channel");
            let on_msg = {
                let identity = identity.clone();
                let booted_account = booted_account.clone();
                let session_expires_at = session_expires_at.clone();
                let expiry_warn = expiry_warn.clone();
                let client = client.clone();
                Closure::<dyn FnMut(MessageEvent)>::new(move |event: MessageEvent| {
                    let Some(data) = event.data().as_string() else {
                        return;
                    };
                    let Ok(obj) = js_sys::JSON::parse(&data) else {
                        return;
                    };

                    let id = js_sys::Reflect::get(&obj, &"identity".into())
                        .ok()
                        .and_then(|v| v.as_string());
                    let expires_at = js_sys::Reflect::get(&obj, &"expiresAt".into())
                        .ok()
                        .and_then(|v| v.as_string())
                        .and_then(|s| s.parse::<u64>().ok());
                    let account = js_sys::Reflect::get(&obj, &"account".into())
                        .ok()
                        .and_then(|v| v.as_string());

                    if let Some(id) = id {
                        identity.set(Some(id));
                    }
                    if let Some(acc) = account {
                        booted_account.set(Some(acc));
                    }
                    if let Some(exp) = expires_at {
                        session_expires_at.set(Some(exp));
                    }

                    // Compute the expiry warning when we have all the inputs.
                    if let (Some(exp_secs), Some(handle)) = (expires_at, (*client).clone()) {
                        let client_inner = (*handle.0).clone();
                        let expiry_warn = expiry_warn.clone();
                        spawn_local(async move {
                            let unsynced = client_inner.with_conn(|conn| conn.unsynced()).await;
                            let now_ms = js_sys::Date::now();
                            // Date.now() is always finite and non-negative (ms since epoch).
                            debug_assert!(now_ms.is_finite() && now_ms >= 0.0);
                            // Deliberate truncation to whole seconds for SystemTime arithmetic.
                            let now_secs = (now_ms / 1000.0) as u64;
                            let now = std::time::SystemTime::UNIX_EPOCH
                                + std::time::Duration::from_secs(now_secs);
                            let expires = std::time::SystemTime::UNIX_EPOCH
                                + std::time::Duration::from_secs(exp_secs);
                            let lead = std::time::Duration::from_secs(7 * 24 * 60 * 60);
                            expiry_warn.set(expiry_warning(now, expires, lead, unsynced));
                        });
                    }
                })
            };
            channel.set_onmessage(Some(on_msg.as_ref().unchecked_ref()));
            move || {
                channel.set_onmessage(None);
                channel.close();
                drop(on_msg);
            }
        });
    }

    // Listen for the worker requesting an interactive login popup.
    {
        let login_url = login_url.clone();
        use_effect_with((), move |()| {
            let channel =
                BroadcastChannel::new(connetto_web::LOGIN_CHANNEL).expect("login channel");
            let on_msg = {
                let login_url = login_url.clone();
                Closure::<dyn FnMut(MessageEvent)>::new(move |event: MessageEvent| {
                    let Some(text) = event.data().as_string() else {
                        return;
                    };
                    let Ok(obj) = js_sys::JSON::parse(&text) else {
                        return;
                    };
                    let kind = js_sys::Reflect::get(&obj, &"kind".into())
                        .ok()
                        .and_then(|v| v.as_string());
                    if kind.as_deref() != Some("request") {
                        return;
                    }
                    if let Some(url) = js_sys::Reflect::get(&obj, &"url".into())
                        .ok()
                        .and_then(|v| v.as_string())
                    {
                        login_url.set(Some(url));
                    }
                })
            };
            channel.set_onmessage(Some(on_msg.as_ref().unchecked_ref()));
            move || {
                channel.set_onmessage(None);
                channel.close();
                drop(on_msg);
            }
        });
    }

    // Respond to the worker's provider query at each boot. The worker sends
    // "provider?" on DEMO_PROVIDER_CHANNEL and this page always replies with
    // the one provider the dev stack registers.
    {
        use_effect_with((), move |()| {
            let ch_recv = BroadcastChannel::new(DEMO_PROVIDER_CHANNEL).expect("provider channel");
            let ch_send = ch_recv.clone();
            let on_msg = Closure::<dyn FnMut(MessageEvent)>::new(move |e: MessageEvent| {
                if e.data().as_string().as_deref() == Some("provider?") {
                    let _ = ch_send.post_message(&JsValue::from_str(AUTH_PROVIDER));
                }
            });
            ch_recv.set_onmessage(Some(on_msg.as_ref().unchecked_ref()));
            move || {
                ch_recv.set_onmessage(None);
                ch_recv.close();
                drop(on_msg);
            }
        });
    }

    // Connect to the DB worker and forward status events.
    {
        let client = client.clone();
        let status = status.clone();
        let boot_hold = boot_hold.clone();
        let custody = custody.clone();
        use_effect_with((), move |()| {
            spawn_local(async move {
                match boot_window().await {
                    Ok(boot) => {
                        custody.set(boot.custody);
                        let mut events = boot.client.events();
                        client.set(Some(ClientHandle(Rc::new(boot.client.clone()))));
                        status.set("connected".to_owned());
                        *boot_hold.borrow_mut() = Some(boot);
                        while let Ok(event) = events.recv().await {
                            if let Some(label) = status_label(&event) {
                                status.set(label);
                            }
                        }
                    }
                    Err(err) => status.set(format!("boot failed: {err:?}")),
                }
            });
            || ()
        });
    }

    let open_login = {
        let login_url = login_url.clone();
        Callback::from(move |_| {
            if let (Some(url), Some(win)) = ((*login_url).clone(), web_sys::window()) {
                let _ = win.open_with_url_and_target_and_features(
                    &url,
                    "_blank",
                    "popup,width=640,height=720",
                );
            }
        })
    };

    let logout_keep = {
        let status = status.clone();
        Callback::from(move |_| {
            let status = status.clone();
            spawn_local(async move {
                match connetto_web::auth::request_logout(false, false).await {
                    Ok(_) => reload_page(),
                    Err(err) => status.set(format!("logout failed: {err}")),
                }
            });
        })
    };

    let logout_delete = {
        let status = status.clone();
        let confirm_seqs = confirm_seqs.clone();
        let refused_seqs = refused_seqs.clone();
        Callback::from(move |_| {
            let status = status.clone();
            let confirm_seqs = confirm_seqs.clone();
            let refused_seqs = refused_seqs.clone();
            spawn_local(async move {
                match connetto_web::auth::request_unsynced().await {
                    Ok(seqs) if seqs.is_empty() => {
                        match connetto_web::auth::request_logout(true, false).await {
                            Ok(connetto_web::auth::LogoutOutcome::Refused { seqs }) => {
                                refused_seqs.set(Some(seqs));
                            }
                            Ok(_) => reload_page(),
                            Err(err) => status.set(format!("logout failed: {err}")),
                        }
                    }
                    Ok(seqs) => confirm_seqs.set(Some(seqs)),
                    Err(err) => status.set(format!("checking unsynced failed: {err}")),
                }
            });
        })
    };

    let confirm_delete = {
        let status = status.clone();
        let confirm_seqs = confirm_seqs.clone();
        Callback::from(move |_| {
            let status = status.clone();
            let confirm_seqs = confirm_seqs.clone();
            spawn_local(async move {
                confirm_seqs.set(None);
                match connetto_web::auth::request_logout(true, true).await {
                    Ok(_) => reload_page(),
                    Err(err) => status.set(format!("forced delete failed: {err}")),
                }
            });
        })
    };

    let force_delete = {
        let status = status.clone();
        let refused_seqs = refused_seqs.clone();
        Callback::from(move |_| {
            let status = status.clone();
            let refused_seqs = refused_seqs.clone();
            spawn_local(async move {
                refused_seqs.set(None);
                match connetto_web::auth::request_logout(true, true).await {
                    Ok(_) => reload_page(),
                    Err(err) => status.set(format!("forced delete failed: {err}")),
                }
            });
        })
    };

    let cancel_confirm = {
        let confirm_seqs = confirm_seqs.clone();
        let refused_seqs = refused_seqs.clone();
        Callback::from(move |_| {
            confirm_seqs.set(None);
            refused_seqs.set(None);
        })
    };

    // Account picker dialog, shown while the worker awaits the user's choice.
    let picker_html = if let Some(accounts) = (*account_picker).clone() {
        let add_new = {
            let pending_choice = pending_choice.clone();
            Callback::from(move |_| {
                *pending_choice.borrow_mut() = Some(AccountChoice::New);
            })
        };
        let switch_buttons: Html = accounts
            .iter()
            .cloned()
            .map(|account| {
                let pending_choice = pending_choice.clone();
                let label = account.clone();
                html! {
                    <button onclick={Callback::from(move |_| {
                        *pending_choice.borrow_mut() =
                            Some(AccountChoice::Named(account.clone()));
                    })}>
                        { format!("Sign in as {label}") }
                    </button>
                }
            })
            .collect();
        html! {
            <div class="picker">
                <strong>{ "Choose account:" }</strong>
                <div class="row">
                    { switch_buttons }
                    <button onclick={add_new}>{ "Add new account" }</button>
                </div>
            </div>
        }
    } else {
        html! {}
    };

    // Expiry warning banner.
    let expiry_html = if let Some(warn) = (*expiry_warn).clone() {
        let count = warn.unsynced.len();
        html! {
            <div class="expiry-warn">
                { format!(
                    "Session nearing expiry with {count} unsynced write(s). \
                     Reconnect before the session lapses to avoid data loss."
                ) }
            </div>
        }
    } else {
        html! {}
    };

    let auth_bar = {
        let account_line = match ((*identity).clone(), (*booted_account).clone()) {
            (Some(uid), Some(acc)) => html! {
                <span>
                    { format!("Signed in as {} (account: {}).", uid, acc) }
                    { " " }
                    { format!("Passkey: {}.", &*custody) }
                </span>
            },
            (Some(uid), None) => html! {
                <span>
                    { format!("Signed in as {}.", uid) }
                    { " " }
                    { format!("Passkey: {}.", &*custody) }
                </span>
            },
            _ => html! {
                <span>
                    { "Signed in (account loading)." }
                    { " " }
                    { format!("Passkey: {}.", &*custody) }
                </span>
            },
        };

        // The login prompt stands only until the account is known.
        let awaiting_login = identity.is_none();
        let action_row = if (*login_url).is_some() && awaiting_login {
            html! {
                <span>
                    { "Interactive sign-in required. " }
                    <button onclick={open_login}>{ "Sign in" }</button>
                </span>
            }
        } else {
            // Switch-account buttons for any known account that is not the live one.
            let switch_buttons: Html = (*known_accounts)
                .iter()
                .filter(|a| (*booted_account).as_deref() != Some(a.as_str()))
                .cloned()
                .map(|account| {
                    let boot_hold = boot_hold.clone();
                    let status = status.clone();
                    let identity = identity.clone();
                    let booted_account = booted_account.clone();
                    let label = account.clone();
                    html! {
                        <button onclick={Callback::from(move |_| {
                            // Cleared before the reboot, not after it. The banner
                            // hides the login prompt while an identity is held, and
                            // the replacement worker may need one, so a stale
                            // identity would hide the very control it is waiting
                            // for. The worker rebroadcasts both once it is up.
                            identity.set(None);
                            booted_account.set(None);
                            let result = {
                                let borrow = boot_hold.borrow();
                                borrow.as_ref().map(|b| b._membership.switch_account(&account))
                            };
                            match result {
                                Some(Ok(())) | None => {}
                                Some(Err(e)) => status.set(format!("switch failed: {e:?}")),
                            }
                        })}>
                            { format!("Switch to {label}") }
                        </button>
                    }
                })
                .collect();
            let add_account = {
                let boot_hold = boot_hold.clone();
                let status = status.clone();
                let identity = identity.clone();
                let booted_account = booted_account.clone();
                Callback::from(move |_| {
                    // Same reason as the switch above, and it matters more here:
                    // adding an account always needs an interactive login, so the
                    // prompt must be reachable. Nothing is reloaded either way,
                    // because the pending choice lives in this page and a reload
                    // would discard it.
                    identity.set(None);
                    booted_account.set(None);
                    let result = {
                        let borrow = boot_hold.borrow();
                        borrow.as_ref().map(|b| b._membership.add_account())
                    };
                    match result {
                        Some(Ok(())) | None => {}
                        Some(Err(e)) => status.set(format!("add account failed: {e:?}")),
                    }
                })
            };
            html! {
                <span>
                    <button onclick={logout_keep}>{ "Log out, keep local data" }</button>
                    { " " }
                    <button onclick={logout_delete}>{ "Delete local data and log out" }</button>
                    { " " }
                    { switch_buttons }
                    <button onclick={add_account}>{ "Add another account" }</button>
                </span>
            }
        };

        let confirm_html = if let Some(seqs) = &*confirm_seqs {
            let count = seqs.len();
            html! {
                <span>
                    { format!("{count} unsynced write(s) will be lost. ") }
                    <button onclick={confirm_delete}>{ "Delete anyway" }</button>
                    { " " }
                    <button onclick={cancel_confirm.clone()}>{ "Cancel" }</button>
                </span>
            }
        } else {
            html! {}
        };

        let refused_html = if let Some(seqs) = &*refused_seqs {
            let count = seqs.len();
            html! {
                <span>
                    { format!("Refused: {count} write(s) still pending. ") }
                    <button onclick={force_delete}>{ "Force delete" }</button>
                    { " " }
                    <button onclick={cancel_confirm}>{ "Cancel" }</button>
                </span>
            }
        } else {
            html! {}
        };

        html! {
            <div class="auth-bar">
                { account_line }
                { action_row }
                { confirm_html }
                { refused_html }
            </div>
        }
    };

    let dashboard = if let Some(handle) = &*client {
        html! { <Dashboard client={handle.clone()} /> }
    } else {
        html! { <p>{ "Connecting to the DB worker and the connetto stack..." }</p> }
    };

    html! {
        <>
            <style>{ CSS }</style>
            <div class="wrap">
                <h1>{ "connetto web demo (Yew)" }</h1>
                <p class="status">{ format!("status: {}", &*status) }</p>
                { picker_html }
                { expiry_html }
                { auth_bar }
                { dashboard }
            </div>
        </>
    }
}

/// The client the dashboard drives, passed once from [`App`] when it is ready.
#[derive(Properties, PartialEq)]
struct DashboardProps {
    client: ClientHandle,
}

#[function_component(Dashboard)]
fn dashboard(props: &DashboardProps) -> Html {
    let client = (*props.client.0).clone();

    let orders = use_live::<_, _, Order>(&client, orders::table.order(orders::id));
    let notes = use_live::<_, _, Note>(&client, notes::table.order(notes::id));

    let order_rows = orders.value();
    let note_rows = notes.value();
    let order_count = order_rows.len();
    let order_sum: i64 = order_rows.iter().map(|row| row.quantity).sum();
    let note_count = note_rows.len();

    let note_text = use_state(String::new);

    // R15 retention readout: tab mirror page footprint, refreshed whenever the
    // covered rows move.
    let footprint = use_state(|| (0_i64, 0_i64));
    {
        let client = client.clone();
        let footprint = footprint.clone();
        let order_count = order_rows.len();
        let note_count = note_rows.len();
        use_effect_with((order_count, note_count), move |_| {
            let client = client.clone();
            let footprint = footprint.clone();
            spawn_local(async move {
                footprint.set(replica_footprint(&client).await);
            });
            || ()
        });
    }
    let (pages, free) = *footprint;
    let kb = pages * 4;

    let newest_order = order_rows.last().map(|o| o.id);

    let add_order = {
        let client = client.clone();
        Callback::from(move |_| {
            let client = client.clone();
            spawn_local(async move {
                let quantity = fresh_quantity();
                let result = client
                    .with_conn(move |conn| {
                        diesel::insert_into(orders::table)
                            .values(orders::quantity.eq(quantity))
                            .execute(conn.conn())
                    })
                    .await;
                if let Err(err) = result {
                    tracing::error!(error = %err, "order insert failed");
                }
            });
        })
    };

    let remove_order = {
        let client = client.clone();
        Callback::from(move |_| {
            if let Some(id) = newest_order {
                let client = client.clone();
                spawn_local(async move {
                    let result = client
                        .with_conn(move |conn| {
                            diesel::delete(orders::table.filter(orders::id.eq(id)))
                                .execute(conn.conn())
                        })
                        .await;
                    if let Err(err) = result {
                        tracing::error!(error = %err, "order remove failed");
                    }
                });
            }
        })
    };

    let on_note_input = {
        let note_text = note_text.clone();
        Callback::from(move |event: InputEvent| {
            let input: HtmlInputElement = event.target_unchecked_into();
            note_text.set(input.value());
        })
    };

    let save_note = {
        let client = client.clone();
        let note_text = note_text.clone();
        Callback::from(move |_| {
            let body = (*note_text).clone();
            if body.is_empty() {
                return;
            }
            let client = client.clone();
            let note_text = note_text.clone();
            spawn_local(async move {
                let id = fresh_note_id();
                let result = client
                    .with_conn(move |conn| {
                        diesel::insert_into(notes::table)
                            .values((notes::id.eq(id), notes::body.eq(body)))
                            .execute(conn.conn())
                    })
                    .await;
                match result {
                    Ok(_) => note_text.set(String::new()),
                    Err(err) => {
                        tracing::error!(error = %err, "note save failed");
                    }
                }
            });
        })
    };

    let tidy = {
        let client = client.clone();
        let footprint = footprint.clone();
        Callback::from(move |_| {
            let client = client.clone();
            let footprint = footprint.clone();
            spawn_local(async move {
                if let Err(err) = client.tidy().await {
                    tracing::error!(error = %err, "free up space failed");
                }
                footprint.set(replica_footprint(&client).await);
            });
        })
    };

    // R26: the export runs in the DB worker, which holds the durable replica
    // and the device-private tier. A tab mirror is in memory and partial.
    let export_status = use_state(|| Option::<String>::None);
    let import_status = use_state(|| Option::<String>::None);
    let import_cb = {
        let import_status = import_status.clone();
        Callback::from(move |event: Event| {
            let input: HtmlInputElement = event.target_unchecked_into();
            if let Some(files) = input.files()
                && let Some(file) = files.get(0)
            {
                let import_status = import_status.clone();
                spawn_local(async move {
                    let message = match workers::request_import(file).await {
                        Ok((outcome, clashes)) => {
                            let mut msg = format!(
                                "{} row(s) restored, {} kept, {} write(s) restored",
                                outcome.rows_restored, outcome.rows_kept, outcome.writes_restored
                            );
                            if clashes > 0 {
                                msg.push_str(&format!(" ({clashes} clash(es) resolved to file)"));
                            }
                            msg
                        }
                        Err(err) => format!("refused: {err}"),
                    };
                    import_status.set(Some(message));
                });
            }
        })
    };
    let export = {
        let export_status = export_status.clone();
        Callback::from(move |_| {
            let export_status = export_status.clone();
            spawn_local(async move {
                let message = match workers::request_export(ExportScope::Everything).await {
                    Ok(bytes) => {
                        let len = bytes.len();
                        match download_bytes(EXPORT_FILE_NAME, &bytes) {
                            Ok(()) => format!("{len} bytes offered as {EXPORT_FILE_NAME}"),
                            Err(err) => format!("download refused: {err:?}"),
                        }
                    }
                    Err(err) => format!("export failed: {err}"),
                };
                export_status.set(Some(message));
            });
        })
    };

    let orders_error = orders.error().map(|err| {
        html! { <p style="color:#b00;">{ format!("orders error: {err}") }</p> }
    });
    let notes_error = notes.error().map(|err| {
        html! { <p style="color:#b00;">{ format!("notes error: {err}") }</p> }
    });

    html! {
        <div class="panes">
            <div class="pane">
                <h2>{ "orders " }<span class="badge synced">{ "synced" }</span></h2>
                <p>{ format!("count {order_count}, total quantity {order_sum}. Converges across every window through Postgres.") }</p>
                <div class="row">
                    <button onclick={add_order}>{ "Add order" }</button>
                    if newest_order.is_some() {
                        <button onclick={remove_order}>{ "Remove newest" }</button>
                    }
                </div>
                { orders_error.unwrap_or_default() }
                <table>
                    <thead><tr><th>{ "id" }</th><th>{ "quantity" }</th></tr></thead>
                    <tbody>
                        { for order_rows.iter().map(|row| {
                            let id = row.id.to_string();
                            html! {
                                <tr key={id.clone()}>
                                    <td>{ id }</td>
                                    <td>{ row.quantity.to_string() }</td>
                                </tr>
                            }
                        }) }
                    </tbody>
                </table>
            </div>
            <div class="pane">
                <h2>{ "notes " }<span class="badge local">{ "device-only" }</span></h2>
                <p>{ format!("count {note_count}. Converges across this device's windows through the DB worker, never the server.") }</p>
                <div class="row">
                    <input type="text" placeholder="note body" value={(*note_text).clone()} oninput={on_note_input} />
                    <button onclick={save_note}>{ "Save note" }</button>
                </div>
                { notes_error.unwrap_or_default() }
                <table>
                    <thead><tr><th>{ "id" }</th><th>{ "body" }</th></tr></thead>
                    <tbody>
                        { for note_rows.iter().map(|row| {
                            let id = row.id.to_string();
                            html! {
                                <tr key={id.clone()}>
                                    <td>{ id }</td>
                                    <td>{ row.body.clone() }</td>
                                </tr>
                            }
                        }) }
                    </tbody>
                </table>
            </div>
            <div class="pane">
                <h2>{ "retention " }<span class="badge trim">{ "R15" }</span></h2>
                <p>{ format!("Replica mirror: {pages} pages (~{kb} KB), {free} free to reclaim. Covered rows: {}.", order_count + note_count) }</p>
                <p>{ "Ending a subscription evicts the rows no live subscription still covers, and the trimming pass hands the freed pages back to storage." }</p>
                <div class="row">
                    <button onclick={tidy}>{ "Free up space" }</button>
                </div>
            </div>
            <div class="pane">
                <h2>{ "your data " }<span class="badge local">{ "R26" }</span></h2>
                <p>{ "Save a zip archive of this device's local data. The archive is not \
                      encrypted and holds every row the device can read: whoever holds \
                      the file holds the data." }</p>
                <p>{ "The DB worker exports, not this window: the worker holds the durable replica and the device-private tier, while a tab mirror is in memory and holds only what its subscriptions cover." }</p>
                <div class="row">
                    <button onclick={export}>{ "Export local data" }</button>
                </div>
                if let Some(message) = (*export_status).clone() {
                    <p style="font-family:monospace;font-size:0.85em;color:#555;">{ message }</p>
                }
                <div class="row">
                    <input type="file" accept=".zip" onchange={import_cb} />
                </div>
                if let Some(message) = (*import_status).clone() {
                    <p style="font-family:monospace;font-size:0.85em;color:#555;">{ message }</p>
                }
            </div>
        </div>
    }
}
